HoldSportPage/Pages/Admin/Index.cshtml.cs
using HoldSportPage.Model;
using HoldSportPage.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HoldSportPage.Pages.Admin
{
   
        public class IndexModel : PageModel
        {
            private IUserRepository _users;

            public User UserLoggedIn { get; private set; }

            public IndexModel(IUserRepository users)
            {
                _users = users;
            }

            public IActionResult OnGet()
            {
                if (_users is null || _users.UserLoggedIn is null || !_users.UserLoggedIn.IsAdmin)
                {
                    return RedirectToPage("/Login");
                }

                UserLoggedIn = _users.UserLoggedIn;

                return Page();
            }
        }
    }

HoldSportPage/Pages/CalculateFee.cshtml.cs
using HoldSportPage.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HoldSportPage.Pages
{
    public class CalculateFeeModel : PageModel
    {
        private readonly MembershipFeeCalculator _calculator;

        public CalculateFeeModel(MembershipFeeCalculator calculator)
        {
            _calculator = calculator;
        }

        [BindProperty]
        public int Age { get; set; }

        [BindProperty]
        public bool IsStudent { get; set; }

        [BindProperty]
        public decimal? Fee { get; set; }

        public void OnPost()
        {
            Fee = _calculator.CalculateFee(Age, IsStudent);
        }
    }
}

HoldSportPage/Pages/Common/Index.cshtml.cs
using HoldSportPage.Model;
using HoldSportPage.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HoldSportPage.Pages.Common
{
    public class IndexModel : PageModel
    {
        private IUserRepository _users;

        public User UserLoggedIn { get; private set; }

        public IndexModel(IUserRepository users)
        {
            _users = users;
        }

        public IActionResult OnGet()
        {
            if (_users is null || _users.UserLoggedIn is null)
            {
                return RedirectToPage("/Login");
            }

            UserLoggedIn = _users.UserLoggedIn;

            return Page();
        }
    }
}

HoldSportPage/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace HoldSportPage.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

HoldSportPage/Pages/Index.cshtml.cs
using HoldSportPage.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HoldSportPage.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private IUserRepository _repo;

        public IndexModel(ILogger<IndexModel> logger, IUserRepository repo)
        {
            _logger = logger;
            _repo = repo;
        }

        public IActionResult OnGet()
        {
            if (_repo is null || _repo.UserLoggedIn is null)
            {
                return RedirectToPage("/Login");
            }

            return Page();
        }
    }
}

HoldSportPage/Pages/Login.cshtml.cs
using HoldSportPage.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HoldSportPage.Pages
{
    public class LoginModel : PageModel
    {
        private IUserRepository _userRepository;

        public LoginModel(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }



        [BindProperty]
        public string Username { get; set; }

        [BindProperty]
        public string Password { get; set; }

        public void OnGet()
        {
        }
        public IActionResult OnPost()
        {
            if (Username == null || Password == null)
            {
                return Page();
            }

            if (!_userRepository.CheckUser(Username, Password))
            {
                return Page();
            }

            return RedirectToPage("Index");
        }
    }
}

HoldSportPage/Pages/Logout.cshtml.cs
using HoldSportPage.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HoldSportPage.Pages
{
    public class LogoutModel : PageModel
    {
        private IUserRepository _userRepository;

        public LogoutModel(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }

        public IActionResult OnGet()
        {
            _userRepository.LogoutUser();

            return RedirectToPage("Index");
        }
    }
}

HoldSportPage/Pages/Medlemmer/DeleteKunde.cshtml.cs
using HoldSportPage.Model;
using HoldSportPage.services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text;

namespace HoldSportPage.Pages.Medlemmer
{
    public class DeleteKundeModel : PageModel
    {
        private IKundeRepository _repo;

        public DeleteKundeModel(IKundeRepository repo)
        {
            _repo = repo;
        }



        public Kunde Kunde { get; private set; }



        public IActionResult OnGet(int nummer)
        {
            Kunde = _repo.HentKunde(nummer);


            return Page();
        }

        public IActionResult OnPostDelete(int nummer)
        {
            _repo.Slet(nummer);

            return RedirectToPage("Index");
        }

        public IActionResult OnPostCancel()
        {
            return RedirectToPage("Index");
        }



    }
}

HoldSportPage/Pages/Medlemmer/Index.cshtml.cs
using HoldSportPage.Model;
using HoldSportPage.services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text;

namespace HoldSportPage.Pages.Medlemmer
{
    public class IndexModel : PageModel
    {
        // instans af kunde repository
        private IKundeRepository _repo;

        // Dependency Injection
        public IndexModel(IKundeRepository repository)
        {
            _repo = repository;
        }


        // property til View'et
        public List<Kunde> Kunder { get; set; }

        [BindProperty]
        public int? SearchNumber { get; set; }
        [BindProperty]
        public string? SearchName { get; set; }
        [BindProperty]
        public string? SearchPhone { get; set; }


        public void OnGet()
        {

            //KundeRepository repo = new KundeRepository(true);

            Kunder = _repo.HentAlleKunder();

        }

        public IActionResult OnPost()
        {
            return RedirectToPage("NyKunde");
        }

        public IActionResult OnPostSearch()
        {
            Kunder = _repo.Search(SearchNumber, SearchName, SearchPhone);
            return Page();
        }

        public IActionResult OnPostSortNumber()
        {
            Kunder = _repo.SortNumber();
            return Page();
        }

        public IActionResult OnPostSortName()
        {
            Kunder = _repo.SortName();
            return Page();
        }
    }
}

HoldSportPage/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HoldSportPage.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

HoldSportPage/Pages/Admin/Index.cshtml
@page
@model HoldSportPage.Pages.Admin.IndexModel
@{
}


<h1>Dette er admin siden</h1>
<p>
    her kan du ...
</p>
<a asp-page="../Index">Tilbage</a>

HoldSportPage/Pages/CalculateFee.cshtml
@page
@model HoldSportPage.Pages.CalculateFeeModel
@{
}
<form method="post">
    <label for="age">Alder:</label>
    <input type="text" id="age" name="age" asp-for="Age" />

    <label for="isStudent">Er du studerende?</label>
    <input type="checkbox" id="isStudent" name="isStudent" asp-for="IsStudent" />

    <input type="submit" value="Beregn kontingent" />
</form>

@if (Model != null && Model.Fee.HasValue)
{
    <p>Kontingent: @Model.Fee.Value</p>
}

HoldSportPage/Pages/Common/Index.cshtml
@page
@model HoldSportPage.Pages.Common.IndexModel
@{
}
<h1>Dette er Fælles siden</h1>
<p>
    her kan du alle de alm ting - bare ikke administrator ting og sager...
</p>
<a asp-page="../Index">Tilbage</a>

HoldSportPage/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HoldSportPage/Pages/Login.cshtml
@page
@model HoldSportPage.Pages.LoginModel
@{
}

<h1>Login page</h1>

<form method="post">
    Name: <input type="text" asp-for="@Model.Username" /><br />
    Pass: <input type="password" asp-for="@Model.Password" /><br />
    <input type="submit" value="Login" class="btn btn-primary" /><br />
</form>

HoldSportPage/Pages/Logout.cshtml
@page
@model HoldSportPage.Pages.LogoutModel
@{
}

HoldSportPage/Pages/Medlemmer/DeleteKunde.cshtml
@page
@model HoldSportPage.Pages.Medlemmer.DeleteKundeModel
@{
}

<h1> Slet et Medlem </h1>

<form method="post">
    <div class="form-group>">
        <label>Medlemsnummer</label> : @Model.Kunde.KundeNummer<br />
        <br />
        <label>Navn</label> : @Model.Kunde.Navn<br />
        <br />
        <label>Medlem telefon</label>  : @Model.Kunde.Tlf<br />
        <br />
       



        <input type="submit" value="Slet Kunde" class="btn btn-danger" asp-page-handler="Delete" asp-route-nummer="@Model.Kunde.KundeNummer" />

        <input type="submit" value="Fortryd" class="btn btn-warning" asp-page-handler="Cancel" />
    </div>
</form>

HoldSportPage/Pages/Medlemmer/EditKunde.cshtml
@page
@model HoldSportPage.Pages.Medlemmer.EditKundeModel
@{
}
<h1>Ændre et Medlemskab</h1>


<form method="post">
    <div class="form-group>">
        <label>Medlemsnummer</label> : @Model.NytKundeNummer<br />
        <input type="hidden" asp-for="@Model.NytKundeNummer" /><br />
        <label class="text text-danger">@Model.ErrorMessage</label><br />
        <br />


        <label>Medlemsnavn</label><br />
        <input class="form-control" asp-for="@Model.NytKundeNavn" /><br />
        <span asp-validation-for="@Model.NytKundeNavn" class="text-danger"></span><br />


        <label>Medlem telefon</label><br />
        <input class="form-control" asp-for="@Model.NytKundetlf" /><br />

        



        @if (Model.Error)
        {
            <input type="submit" value="Ændre Ny Kunde" class="btn btn-secondary" asp-page-handler="Change" disabled />
        }
        else
        {
            <input type="submit" value="Ændre Ny Kunde" class="btn btn-success" asp-page-handler="Change" />
        }
        <input type="submit" value="Fortryd" class="btn btn-danger" asp-page-handler="Cancel" />
    </div>
</form>

HoldSportPage/Pages/Medlemmer/Index.cshtml
@page
@using HoldSportPage.Model;
@model HoldSportPage.Pages.Medlemmer.IndexModel
@{
    ViewData["Title"] = "Medlemmer";
}
<h1 class="jumbotron">Vis Alle Medlemmer</h1>

<form method="post">
    Vil du oprette et nyt medlem tryk på <input type="submit" value="Opret" class="btn btn-outline-primary" />
</form>

<p></p>
<form method="post" class="border border-success rounded">
    <input type="submit" asp-page-handler="Search" value="Søg" class="btn btn-outline-success" />
    Kunde Nummer <input type="number" asp-for="@Model.SearchNumber" />
    Kunde Navn <input type="text" asp-for="@Model.SearchName" />
    Kunde Tlf <input type="text" asp-for="@Model.SearchPhone" />
</form>
<p></p>

<table class="table table-hover">
    <thead>
        <tr>
            <form method="post">
            <th><input type="submit" asp-page-handler="SortNumber" value="Kunde Nummer" class="btn btn-outline-success" /></th>
            <th><input type="submit" asp-page-handler="SortName" value="Navn" class="btn btn-outline-success" /></th>
            <th>Telefon</th>
            
            <th></th>
            <th></th>
            </form>
        </tr>
    </thead>
    <tbody>
        @foreach (Kunde k in Model.Kunder)
        {
            <tr>
                <td>@k.KundeNummer</td>
                <td>@k.Navn</td>
                <td>@k.Tlf</td>
                
                <td><a asp-page="EditKunde" asp-route-nummer="@k.KundeNummer">Ændre</a></td>
                <td><a asp-page="DeleteKunde" asp-route-nummer="@k.KundeNummer">Slet</a></td>
            </tr>
        }
    </tbody>
</table>

HoldSportPage/Pages/Medlemmer/NyKunde.cshtml
@page
@model HoldSportPage.Pages.Medlemmer.NyKundeModel
@{
}
<h1>Opret et nyt medlem</h1>


<form method="post">
    <div class="form-group>">
        <label>Kunde nummer</label><br />
        <input class="form-control" asp-for="@Model.NytKundeNummer" /><br />
        <label class="text text-danger">@Model.ErrorMessage</label><br />
        <br />

        <label>Kunde navn</label><br />
        <input class="form-control" asp-for="@Model.NytKundeNavn" /><br />
        <span asp-validation-for="@Model.NytKundeNavn" class="text-danger"></span><br />
        <br />

        <label>Kunde telefon</label><br />
        <input class="form-control" asp-for="@Model.NytKundetlf" /><br />

        


        <input type="submit" value="Opret Ny Kunde" class="btn btn-success" />
        <input type="submit" value="Fortryd" class="btn btn-danger" asp-page-handler="Cancel" />
    </div>
</form>

HoldSportPage/Pages/Shared/_Layout.cshtml
@inject HoldSportPage.Services.IUserRepository Users
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Holdsport</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ClassDemoTestLogin.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">HoldSport</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="Index">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Medlemmer/Index">Medlemmer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/common/Index">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Model/MembershipFeeCalculator">Kontigent</a>
                        </li>
                        @if (Users.UserLoggedIn is not null && Users.UserLoggedIn.IsAdmin)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/admin/Index">Admin</a>
                            </li>
                        }
                        @if (Users.UserLoggedIn is not null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HoldSport - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>